name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-lint:
    name: PHP + Node checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_sqlite
          coverage: none
          tools: composer
          ini-values: error_reporting=E_ALL
        
      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install NPM dependencies
        run: npm ci

      - name: Lint PHP (mago)
        run: composer lint

      - name: Lint JS/TS (ESLint)
        run: npm run lint

      - name: Type check (TypeScript)
        run: npm run types

      - name: Run tests (PHPUnit)
        env:
          APP_ENV: testing
        run: composer test

